In [ ]:
# Objective:
# To build a strong foundation in using NumPy for numerical computations,
# including creating arrays, performing operations, and leveraging its
# powerful functionalities.  {NUMPY QUESTION's}

In [ ]:
                                                         # Task 1: Creating Arrays

In [ ]:
# Task 1: Creating Arrays -->Question -1 

In [22]:
import numpy as np
arr = np.random.randint(1, 11, 10)
print(arr.shape)
print(arr.size)
print(type(arr))
arr


(10,)
10
<class 'numpy.ndarray'>


array([ 7,  6,  4, 10,  2,  6,  7,  2,  7,  1], dtype=int32)

In [ ]:
# Task 1: Creating Arrays -->Question -2

In [23]:
import numpy as np
matrix = np.random.randint(1, 10, 9).reshape(3, 3)
print(matrix.shape)
print(matrix.size)
print(type(matrix))
matrix


(3, 3)
9
<class 'numpy.ndarray'>


array([[7, 6, 3],
       [9, 1, 5],
       [7, 1, 2]], dtype=int32)

In [ ]:
# Task 1: Creating Arrays -->Question -3

In [24]:
import numpy as np
tensor = np.random.rand(3, 5, 3)
print(tensor.shape)
print(tensor.size)
print(type(tensor))
tensor


(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.75398842, 0.55817699, 0.14516893],
        [0.42511411, 0.47350746, 0.7426744 ],
        [0.47507712, 0.18250048, 0.10816854],
        [0.8486509 , 0.37286407, 0.52475962],
        [0.20369459, 0.23706776, 0.86384732]],

       [[0.76131211, 0.77289139, 0.82646691],
        [0.04878354, 0.53152273, 0.50479042],
        [0.6960166 , 0.41049635, 0.75589485],
        [0.91361839, 0.36679062, 0.67611662],
        [0.87895932, 0.23556166, 0.97497042]],

       [[0.48985614, 0.21517026, 0.89850478],
        [0.14202736, 0.93895041, 0.96414724],
        [0.73555042, 0.97406869, 0.85051456],
        [0.73851712, 0.18116298, 0.34675745],
        [0.21484894, 0.21728179, 0.94304311]]])

In [ ]:
                                              #Task 2: Array Indexing and Slicing

In [10]:
import numpy as np
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
print(arr[0:3])    #1
print(arr[::2])    #2
print(arr[::-1])   #3


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [ ]:
                                              #Task 3: Mathematical Operations

In [ ]:
#Task 3: Mathematical Operations --->Question -1 and Question-2[i]

In [31]:
import numpy as np
x = np.random.randint(1, 20, 5)
y = np.random.randint(1, 20, 5)
print(x)
print(y)
addition = x + y
subtraction = x - y
multiplication = x * y
division = x / y
print("Addition :", addition)
print("Subtraction :", subtraction)
print("Multiplication :", multiplication)
print("Division:", division)


[ 1 11 12  3 13]
[ 6  7  2  6 10]
Addition : [ 7 18 14  9 23]
Subtraction : [-5  4 10 -3  3]
Multiplication : [  6  77  24  18 130]
Division: [0.16666667 1.57142857 6.         0.5        1.3       ]


In [ ]:
#Task 3: Mathematical Operations --->Question-2[i]

In [32]:
x = np.random.randint(1, 20, 5)
y = np.random.randint(1, 20, 5)
print(x)
print(y)
dot_product = np.dot(x, y)
print(dot_product)

[ 2 15  6  1 14]
[12  2 11 19 13]
321


In [ ]:
#Task 3: Mathematical Operations --->Question-2[iii]

In [33]:
arr = np.random.randint(1, 20, 5)
brr = np.random.randint(1, 20, 5)
print(arr)
print("Mean :", np.mean(arr))
print("Median :", np.median(arr))
print("Standard deviation :", np.std(arr))
print("Varience :", np.var(arr))

[ 2  5 19  7  2]
Mean : 7.0
Median : 5.0
Standard deviation : 6.29285308902091
Varience : 39.6


In [ ]:
#Task 3: Mathematical Operations --->Question-2[iv]

In [34]:
arr1 = np.random.randint(1, 20, 5)
arr2 = np.random.randint(1, 20, 5)
print(arr2)
print("Maximum :", np.max(arr2))
print("Minimum :", np.min(arr2))
print("Maximum idx :", np.argmax(arr2))
print("Minimum idx :", np.argmin(arr2))

[11  8  1  7  6]
Maximum : 11
Minimum : 1
Maximum idx : 0
Minimum idx : 2


In [ ]:
                                              # Task 4: Reshaping and Transposing

In [15]:
import numpy as np

l1=np.random.randint(1,12,12)                 #1
print(l1)   
print("2D Array of Size 4X3")                 #2
print(l1.reshape(4,3))
print("3D Array of Size 2X2X3  ")             #3
print(l1.reshape(2,2,3))
print("Transpose of 2D Array")                #4
print(np.transpose(l1.reshape(4,3)))  
print("Transpose of 2D Array and its shape")  #5
print(np.transpose(l1.reshape(4,3)).shape)


[ 2  5 10  7  3 11  2  8  6  8  3 11]
2D Array of Size 4X3
[[ 2  5 10]
 [ 7  3 11]
 [ 2  8  6]
 [ 8  3 11]]
3D Array of Size 2X2X3  
[[[ 2  5 10]
  [ 7  3 11]]

 [[ 2  8  6]
  [ 8  3 11]]]
Transpose of 2D Array
[[ 2  7  2  8]
 [ 5  3  8  3]
 [10 11  6 11]]
Transpose of 2D Array and its shape
(3, 4)


In [ ]:
                                            # Task 5: Boolean Masking and Filtering

In [16]:
import numpy as np

l2=np.random.randint(10,50,15) #1
print(l2)
print("Numbers Greater than 25 :")                      #2[i]
print(l2[l2>25])
print("Replacing all elements less than 30 with 0 :")   #2[ii]
l2[l2<30]=0
print(l2)
print("number of nonZero elements divisible by 5")
print(np.count_nonzero(l2[l2%5==0]))
print("number of  elements divisible by 5")            #2[iii]
print(np.count_nonzero(l2%5==0))


[12 39 18 10 49 31 23 25 12 16 25 37 14 37 26]
Numbers Greater than 25 :
[39 49 31 37 37 26]
Replacing all elements less than 30 with 0 :
[ 0 39  0  0 49 31  0  0  0  0  0 37  0 37  0]
number of nonZero elements divisible by 5
0
number of  elements divisible by 5
10


In [ ]:
                                            # Task 6: Working with Built-in Functions

In [ ]:
# Task 6: Working with Built-in Functions -->Question 1

In [37]:
import numpy as np
arr = np.linspace(0, 1, 10)
print("Array of 10 equally spaced values between 0 and 1 \n")
print(arr)


Array of 10 equally spaced values between 0 and 1 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [36]:
# Task 6: Working with Built-in Functions -->Question 2

In [19]:
# Question -->Create an identity matrix of size 4x4.
import numpy as np
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# Task 6: Working with Built-in Functions -->Question 3

In [38]:
# Question-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

import numpy as np
l3=np.random.randint(1,100,20)
print("Original Array :-")
print(l3)
print("Sorted Array :-")
print(np.sort(l3))
print("5 largest elements")
print(np.sort(l3)[-5:][::-1])

Original Array :-
[49 71 80 31 49 39 39 51 56 14 25 75 15 35 93 80 59 65 21 98]
Sorted Array :-
[14 15 21 25 31 35 39 39 49 49 51 56 59 65 71 75 80 80 93 98]
5 largest elements
[98 93 80 80 75]


In [ ]:
                                                     # Task 7: Generic

In [39]:
import numpy as np
import time

# Generate two random matrices of size 100x100
mat1 = np.random.rand(100, 100)
mat2 = np.random.rand(100, 100)

# Record the starting time
start = time.time()
print(f"Computation started at: {start} \n")

# Perform matrix multiplication
result = np.dot(mat1, mat2)
print("Matrix multiplication finished.\n")
print(result, "\n")

# Compute the determinant of the resulting matrix
det_result = np.linalg.det(result)
print(f"Determinant of the product matrix: {det_result} \n")

# Attempt to compute the inverse if the determinant is not zero
if np.isclose(det_result, 0):
    inv_result = None
    is_invertible = False
else:
    inv_result = np.linalg.inv(result)
    is_invertible = True

# Record the ending time
end = time.time()
print(f"Computation ended at: {end} \n")

duration = end - start

# Display final outcomes
print("The matrix is invertible." if is_invertible else "The matrix is not invertible.")
if is_invertible:
    print("Inverse matrix computed successfully.")
    print(inv_result, "\n")
print(f"Total computation time: {duration:.4f} seconds")

Computation started at: 1751909606.4175298 

Matrix multiplication finished.

[[21.74254122 25.44103205 24.32894808 ... 23.73048632 24.33635375
  25.44090315]
 [20.97127132 23.72597113 23.51843954 ... 21.37091226 23.71670418
  24.51849653]
 [23.58696795 25.23709277 24.45243081 ... 25.04703926 28.30502179
  26.48922102]
 ...
 [22.54686934 24.54055599 23.06247668 ... 21.17237669 23.82617547
  24.59468198]
 [20.89241961 24.75502856 24.38308333 ... 22.08893292 24.0014092
  23.18312425]
 [23.13404791 24.80609927 25.54686826 ... 21.93043963 26.74923871
  26.72779287]] 

Determinant of the product matrix: 7.67965861666286e+50 

Computation ended at: 1751909606.4817755 

The matrix is invertible.
Inverse matrix computed successfully.
[[-2.1253738  -0.09738814 -0.86112033 ...  1.82340978 -0.45713319
  -0.44354172]
 [ 1.59312351  1.91383098  1.09202629 ... -2.16277056 -0.03902213
   1.45210785]
 [ 0.61672546  0.73306963  1.20310796 ... -1.22481773  1.09155856
   0.4209182 ]
 ...
 [ 0.45915648 -0